import {StyleSheet} from 'react-native';
import {
  background_cream_color,
  surface_white_color,
  text_primary_brown_color,
  text_dark_gray_color,
  text_muted_gray_color,
  border_soft_brown_color,
  border_light_gray_color,
  accent_indigo_light_color,
  shadow_black_color,
  icon_gray_color,
} from './colors';

export const conversationStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: background_cream_color,
  },
  conversationBox: {
    flex: 1,
    backgroundColor: background_cream_color,
  },
  conversationContent: {
    padding: 8,
    paddingBottom: 20,
  },
  headerContainer: {
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: surface_white_color,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
  },
  headerLeft: {
    width: 36,
    height: 36,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: text_primary_brown_color,
    fontFamily: 'Patrick Hand',
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
    zIndex: -1,
  },
  headerRight: {
    width: 36,
    height: 36,
  },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerButtonImage: {
    width: 24,
    height: 24,
  },
  avatarRow: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 4,
    width: '100%',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#000000',
    overflow: 'hidden',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: surface_white_color,
  },
  parrotAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#000000',
    overflow: 'hidden',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: surface_white_color,
  },
  userAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#000000',
    overflow: 'hidden',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: surface_white_color,
  },
  avatarImage: {
    width: 60,
    height: 60,
    position: 'absolute',
    left: 5,
    top: 2,
  },
  userImageShift: {
    width: 60,
    height: 60,
    position: 'absolute',
    left: -7,
    top: -7,
  },
  userAvatarImage: {
    width: 65,
    height: 65,
    position: 'absolute',
    left: -10,
    top: -10,
  },
  parrotImageShift: {
    width: 60,
    height: 60,
    position: 'absolute',
    left: -7,
    top: -7,
  },
  messageContainer: {
    marginBottom: 10,
    maxWidth: '85%',
    padding: 12,
    borderRadius: 16,
    backgroundColor: surface_white_color,
    borderWidth: 1,
    borderColor: '#000000',
  },
  userMessageContainer: {
    alignSelf: 'flex-start',
    backgroundColor: surface_white_color,
  },
  agentMessageContainer: {
    alignSelf: 'flex-start',
    backgroundColor: surface_white_color,
  },
  agentName: {
    fontSize: 14,
    fontWeight: '600',
    color: accent_indigo_light_color,
    marginBottom: 4,
    fontFamily: 'Patrick Hand',
  },
  speakerNameContainer: {
    marginLeft: 64,
    marginBottom: 4,
  },
  userName: {
    fontSize: 14,
    fontWeight: '600',
    color: text_primary_brown_color,
    marginBottom: 4,
    fontFamily: 'Patrick Hand',
  },
  messageText: {
    fontSize: 17,
    lineHeight: 24,
    marginBottom: 8,
    color: text_dark_gray_color,
    fontFamily: 'Patrick Hand',
  },
  userMessageText: {
    color: text_dark_gray_color,
  },
  agentMessageText: {
    color: text_dark_gray_color,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  loadingText: {
    marginLeft: 8,
    color: text_muted_gray_color,
    fontSize: 16,
    fontFamily: 'Patrick Hand',
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: background_cream_color,
    alignItems: 'center',
    gap: 8,
  },
  textInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 100,
    backgroundColor: surface_white_color,
    borderRadius: 23,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 17,
    color: text_dark_gray_color,
    borderWidth: 1,
    borderColor: '#000000',
    fontFamily: 'Patrick Hand',
    textAlignVertical: 'center',
  },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: surface_white_color,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  sendButtonDisabled: {
    backgroundColor: '#cccccc',
    borderColor: '#999999',
  },
  sendButtonImage: {
    width: 24,
    height: 24,
  },
  sendButtonText: {
    color: '#000000',
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Patrick Hand',
  },
  streamingCursor: {
    color: accent_indigo_light_color,
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Patrick Hand',
  },
  articleTab: {
    marginTop: 8,
    alignItems: 'flex-start',
  },
  articleTabIndicator: {
    width: 4,
    height: 16,
    backgroundColor: '#999999',
    borderRadius: 2,
  },
  systemMessageContainer: {
    alignItems: 'center',
    marginVertical: 8,
    paddingHorizontal: 16,
  },
  systemMessageText: {
    fontSize: 12,
    color: text_muted_gray_color,
    fontFamily: 'Patrick Hand',
    textAlign: 'center',
  },
});

