import {StyleSheet} from 'react-native';
import {
  background_cream_color,
  surface_white_color,
  text_primary_brown_color,
  text_dark_gray_color,
  text_muted_gray_color,
  border_soft_brown_color,
  border_light_gray_color,
  accent_indigo_light_color,
  shadow_black_color,
  icon_gray_color,
} from './colors';

export const conversationStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: background_cream_color,
  },
  conversationBox: {
    flex: 1,
    backgroundColor: background_cream_color,
  },
  conversationContent: {
    padding: 16,
    paddingBottom: 20,
  },
  headerContainer: {
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: background_cream_color,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: border_soft_brown_color,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: text_primary_brown_color,
  },
  headerMenu: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D7D1C6',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: surface_white_color,
  },
  headerMenuIcon: {
    width: 16,
    height: 12,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: icon_gray_color,
  },
  avatarRow: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
  },
  parrotAvatar: {
    width: 46,
    height: 46,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: text_primary_brown_color,
    overflow: 'hidden',
    backgroundColor: surface_white_color,
    marginRight: 10,
  },
  userAvatar: {
    width: 46,
    height: 46,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: text_primary_brown_color,
    overflow: 'hidden',
    backgroundColor: surface_white_color,
    marginRight: 10,
  },
  userImageShift: {
    width: 60,
    height: 60,
    position: 'absolute',
    left: -9,
    top: -10,
  },
  parrotImageShift: {
    width: 88,
    height: 88,
    position: 'absolute',
    left: 1,
    top: 2,
  },
  messageContainer: {
    marginBottom: 16,
    maxWidth: '85%',
    padding: 12,
    borderRadius: 16,
    backgroundColor: surface_white_color,
  },
  userMessageContainer: {
    alignSelf: 'flex-start',
    backgroundColor: surface_white_color,
  },
  agentMessageContainer: {
    alignSelf: 'flex-start',
    backgroundColor: surface_white_color,
    shadowColor: shadow_black_color,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  agentName: {
    fontSize: 12,
    fontWeight: '600',
    color: accent_indigo_light_color,
    marginBottom: 6,
  },
  userName: {
    fontSize: 12,
    fontWeight: '600',
    color: text_primary_brown_color,
    marginBottom: 6,
  },
  messageText: {
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
    color: text_dark_gray_color,
  },
  userMessageText: {
    color: text_dark_gray_color,
  },
  agentMessageText: {
    color: text_dark_gray_color,
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
  },
  loadingText: {
    marginLeft: 8,
    color: text_muted_gray_color,
    fontSize: 14,
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: surface_white_color,
    borderTopWidth: 1,
    borderTopColor: border_light_gray_color,
    alignItems: 'flex-end',
  },
  textInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 100,
    backgroundColor: background_cream_color,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: text_dark_gray_color,
    marginRight: 8,
    borderWidth: 1,
    borderColor: border_light_gray_color,
  },
  sendButton: {
    backgroundColor: accent_indigo_light_color,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    minWidth: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: '#cccccc',
  },
  sendButtonText: {
    color: surface_white_color,
    fontSize: 16,
    fontWeight: '600',
  },
  streamingCursor: {
    color: accent_indigo_light_color,
    fontSize: 16,
    fontWeight: 'bold',
  },
  restartButtonContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 4,
    backgroundColor: background_cream_color,
    borderBottomWidth: 1,
    borderBottomColor: border_light_gray_color,
    alignItems: 'flex-end',
  },
  restartButton: {
    backgroundColor: surface_white_color,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: border_light_gray_color,
    shadowColor: shadow_black_color,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  restartButtonText: {
    color: text_muted_gray_color,
    fontSize: 14,
    fontWeight: '600',
  },
});

