import {StyleSheet} from 'react-native';
import {
  background_cream_color,
  surface_white_color,
  text_primary_brown_color,
  text_dark_gray_color,
  text_muted_gray_color,
  border_soft_brown_color,
  border_light_gray_color,
  shadow_black_color,
  icon_gray_color,
} from './colors';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: background_cream_color,
  },
  headerContainer: {
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: surface_white_color,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
  },
  headerLeft: {
    width: 36,
    height: 36,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: text_primary_brown_color,
    fontFamily: 'Patrick Hand',
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
    zIndex: -1,
  },
  headerRight: {
    width: 36,
    height: 36,
  },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerButtonImage: {
    width: 24,
    height: 24,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 20,
  },
  greetingBanner: {
    backgroundColor: surface_white_color,
    borderRadius: 24,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: text_primary_brown_color,
  },
  greetingText: {
    fontSize: 26,
    fontWeight: '700',
    color: text_primary_brown_color,
    textAlign: 'center',
    fontFamily: 'Patrick Hand',
  },
  pollyCard: {
    backgroundColor: surface_white_color,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: text_primary_brown_color,
    alignItems: 'center',
    shadowColor: shadow_black_color,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  pollyImageContainer: {
    width: 180,
    height: 180,
    overflow: 'hidden',
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pollyImage: {
    width: 180,
    height: 180,
  },
  pollyName: {
    fontSize: 22,
    fontWeight: '700',
    color: text_primary_brown_color,
    marginBottom: 8,
    fontFamily: 'Patrick Hand',
  },
  pollySpeechBubble: {
    backgroundColor: surface_white_color,
    borderRadius: 16,
    padding: 12,
    marginTop: 8,
    borderWidth: 2,
    borderColor: text_primary_brown_color,
    maxWidth: '90%',
  },
  pollySpeechText: {
    fontSize: 16,
    color: text_dark_gray_color,
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: 'Patrick Hand',
  },
  pollyInstruction: {
    fontSize: 14,
    color: text_muted_gray_color,
    marginTop: 8,
    textAlign: 'center',
    fontStyle: 'italic',
    fontFamily: 'Patrick Hand',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: text_primary_brown_color,
    marginBottom: 16,
    marginTop: 8,
    fontFamily: 'Patrick Hand',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: border_soft_brown_color,
    marginBottom: 16,
  },
  birdGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  birdCard: {
    width: '48%',
    backgroundColor: surface_white_color,
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: text_primary_brown_color,
    alignItems: 'center',
    shadowColor: shadow_black_color,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  birdImageContainer: {
    width: 100,
    height: 100,
    overflow: 'hidden',
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  birdImage: {
    width: 100,
    height: 100,
  },
  birdName: {
    fontSize: 16,
    fontWeight: '700',
    color: text_primary_brown_color,
    marginBottom: 4,
    textAlign: 'center',
    fontFamily: 'Patrick Hand',
  },
  birdCategory: {
    fontSize: 14,
    color: text_muted_gray_color,
    textAlign: 'center',
    fontFamily: 'Patrick Hand',
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyStateText: {
    fontSize: 18,
    color: text_muted_gray_color,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'Patrick Hand',
  },
  emptyStateButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: text_primary_brown_color,
    backgroundColor: surface_white_color,
  },
  emptyStateButtonText: {
    fontSize: 18,
    color: text_primary_brown_color,
    fontFamily: 'Patrick Hand',
    fontWeight: '600',
  },
  allBirdsLinkContainer: {
    marginTop: 8,
    marginBottom: 16,
    alignItems: 'center',
  },
  allBirdsLinkText: {
    fontSize: 16,
    color: text_primary_brown_color,
    textDecorationLine: 'underline',
    fontFamily: 'Patrick Hand',
  },
  chatInputContainer: {
    flexDirection: 'row',
    marginTop: 16,
    alignItems: 'center',
    gap: 8,
    width: '100%',
  },
  chatTextInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 100,
    backgroundColor: surface_white_color,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 17,
    color: text_dark_gray_color,
    borderWidth: 2,
    borderColor: '#000000',
    fontFamily: 'Patrick Hand',
    textAlignVertical: 'center',
  },
  chatSendButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: surface_white_color,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  chatSendButtonDisabled: {
    backgroundColor: '#cccccc',
    borderColor: '#999999',
  },
  chatSendButtonImage: {
    width: 24,
    height: 24,
  },
});

