import {StyleSheet} from 'react-native';
import {
  background_cream_color,
  surface_white_color,
  text_primary_brown_color,
  text_dark_gray_color,
  text_muted_gray_color,
} from './colors';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: background_cream_color,
  },
  headerContainer: {
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: surface_white_color,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
  },
  headerLeft: {
    width: 36,
    height: 36,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: text_primary_brown_color,
    fontFamily: 'Patrick Hand',
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
    zIndex: -1,
  },
  headerRight: {
    width: 36,
    height: 36,
  },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerButtonImage: {
    width: 24,
    height: 24,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: surface_white_color,
    borderBottomWidth: 1,
    borderBottomColor: '#000000',
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    height: 50,
    alignItems: 'flex-end',
    gap: 0,
  },
  tabButton: {
    flex: 1,
    height: 50,
    paddingHorizontal: 0,
    paddingVertical: 12,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 1,
    borderTopWidth: 0,
    borderColor: '#000000',
    backgroundColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  tabButtonActive: {
    backgroundColor: background_cream_color,
    zIndex: 2,
    borderBottomWidth: 1,
    borderBottomColor: background_cream_color,
    marginBottom: -1,
  },
  tabButtonText: {
    fontSize: 20,
    fontFamily: 'Patrick Hand',
    fontWeight: '700',
    color: text_muted_gray_color,
  },
  tabButtonTextActive: {
    color: text_primary_brown_color,
    fontWeight: '700',
  },
  tabContent: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    paddingBottom: 32,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  section: {
    marginBottom: 24,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: 24,
  },
  sectionHeader: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: text_dark_gray_color,
    fontFamily: 'Patrick Hand',
    marginBottom: 16,
  },
  sectionSubtitle: {
    fontSize: 16,
    fontWeight: '400',
    color: text_dark_gray_color,
    fontFamily: 'Patrick Hand',
    marginTop: 4,
  },
  menuButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
  },
  menuButtonImage: {
    width: 18,
    height: 18,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    marginBottom: 8,
  },
  input: {
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    paddingHorizontal: 16,
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    backgroundColor: surface_white_color,
    color: text_dark_gray_color,
  },
  inputInactive: {
    backgroundColor: '#F5F5F5',
  },
  dateInputContainer: {
    flexDirection: 'row',
    gap: 8,
    width: '100%',
    maxWidth: '100%',
  },
  dateInput: {
    flex: 1,
    minWidth: 0, // Allow shrinking below content size
    maxWidth: '33%', // Each input takes max 1/3 of container
  },
  topicsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  topicButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000000',
    minWidth: '45%',
    minHeight: 50,
    justifyContent: 'center',
  },
  topicButtonText: {
    fontSize: 16,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    textAlign: 'center',
  },
  saveButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: surface_white_color,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
    marginTop: 16,
  },
  saveButtonText: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    fontWeight: '600',
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  timeButton: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '45%',
  },
  timeIcon: {
    fontSize: 22,
    marginBottom: 4,
  },
  timeButtonText: {
    fontSize: 14,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    textAlign: 'center',
  },
  dropdown: {
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: surface_white_color,
  },
  dropdownText: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
  },
  dropdownArrow: {
    fontSize: 14,
    color: text_dark_gray_color,
  },
  dropdownOptions: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    backgroundColor: surface_white_color,
    overflow: 'hidden',
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  dropdownOptionSelected: {
    backgroundColor: '#E3F2FD',
  },
  dropdownOptionText: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
  },
  dropdownOptionTextSelected: {
    fontWeight: '600',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingVertical: 8,
  },
  toggleLabel: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
  },
  privacyOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  privacyOptionText: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
  },
  parrotRenameSection: {
    marginBottom: 24,
  },
  parrotRenameHint: {
    fontSize: 16,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    marginBottom: 12,
  },
  parrotRenameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    maxWidth: '100%',
  },
  parrotNameInput: {
    flex: 1,
    minWidth: 0, // Allow shrinking below content size
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 10,
    paddingHorizontal: 16,
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    backgroundColor: surface_white_color,
    textAlignVertical: 'center',
  },
  parrotNameSaveButton: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: surface_white_color,
    alignItems: 'center',
    justifyContent: 'center',
  },
  parrotNameSaveButtonText: {
    fontSize: 18,
    fontFamily: 'Patrick Hand',
    color: text_dark_gray_color,
    fontWeight: '600',
  },
});

